version: 1.0.{build}

clone_depth: 1

branches:
    only:
        - main

environment:
    matrix:
        - job_name: Windows x64
          appveyor_build_worker_image: Visual Studio 2022
          platform: x64

        # - job_name: Windows ARM
        #   appveyor_build_worker_image: Visual Studio 2022
        #   platform: ARM

        - job_name: Windows x86
          appveyor_build_worker_image: Visual Studio 2019

        - job_name: Linux x64
          appveyor_build_worker_image: Ubuntu2204

        - job_name: Linux x86
          appveyor_build_worker_image: Ubuntu2204

        - job_name: macOS Monterey
          appveyor_build_worker_image: macos-monterey

matrix:
    fast_finish: true

for:
    - matrix:
          only:
              - job_name: Windows x64

      build_script:
          - cmd: mkdir Build
          - cmd: cd Build
          - cmd: cmake -A x64 ..
          - cmd: cmake --build .

      test_script:
          - cmd: ctest -C Debug

    # - matrix:
    #       only:
    #           - job_name: Windows ARM

    #   build_script:
    #       - cmd: mkdir Build
    #       - cmd: cd Build
    #       - cmd: cmake ..
    #       - cmd: cmake --build .

    #   test_script:
    #       - cmd: ctest -C Debug

    - matrix:
          only:
              - job_name: Windows x86

      build_script:
          - cmd: mkdir Build
          - cmd: cd Build
          - cmd: cmake -A Win32 ..
          - cmd: cmake --build .

      test_script:
          - cmd: ctest -C Debug

    - matrix:
          only:
              - job_name: Linux x64

      build_script:
          - sh: mkdir Build
          - sh: g++ -std=c++17 -g -O0 -Wall -Wextra -fno-exceptions -march=native -D QENTEM_SSE2=1 ./Tests/Test.cpp -I ./Include -o ./Build/QTest.bin

      test_script:
          - sh: ./Build/QTest.bin

    - matrix:
          only:
              - job_name: Linux x86

      install:
          - sudo apt update
          - sudo apt -y install gcc-multilib g++-multilib

      build_script:
          - sh: mkdir Build
          - sh: g++ -std=c++11 -g -O0 -m32 -Wall -Wextra -fno-exceptions -march=native ./Tests/Test.cpp -I ./Include -o ./Build/QTest.bin

      test_script:
          - sh: ./Build/QTest.bin

    - matrix:
          only:
              - job_name: macOS Monterey

      build_script:
          - sh: mkdir Build
          - sh: clang++ -std=c++11 -g -O0 -Wall -Wextra -fno-exceptions -march=native ./Tests/Test.cpp -I ./Include -o ./Build/QTest.bin

      test_script:
          - sh: ./Build/QTest.bin
